


// import { Product } from "@/types/product";



// const shopData: Product[] = [

//   {
//     title: "IMAXIA Professional Nano Shampoo (1000ml)",
//     description:
//       "Hair-strengthening shampoo formulated for after-smoothing service. Gently cleanses and detangles while helping repair damaged hair, reduce hair fall, and improve softness. Enriched with Argan Oil, plant-based linoline, and hydrolysed collagen complex for heat styling protection.",
//     category: "Televisions",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 1,
//     imgs: {
//       thumbnails: ["/images/products/nanoshampoo1000ml-removebg-preview.png"],
//       previews: ["/images/products/nanoshampoo1000ml-removebg-preview.png"],
//     },
//   },
//   {
//     title: "IMAXIA Professional Nano Shampoo (300ml)",
//     description:
//       "Hair-strengthening shampoo formulated for after-smoothing service. Gently cleanses and detangles while helping repair damaged hair, reduce hair fall, and improve softness. Enriched with Argan Oil, plant-based linoline, and hydrolysed collagen complex for heat styling protection.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 2,
//     imgs: {
//       thumbnails: ["/images/products/nanoshampoo.jpeg"],
//       previews: ["/images/products/nanoshampoo.jpeg"],
//     },
//   },
//   {
//     title: "IMAXIA Professional Nanoplastia Treatment (1000ml)",
//     description:
//       "Formaldehyde-free single-sitting nanoplastia treatment designed to repair damaged hair, reduce frizz, and improve texture. Infused with amino acids, Argan Oil, and Acai Berry to seal the cuticle, lock in moisture, and deliver smooth, shiny, frizz-free results.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 3,
//     imgs: {
//       thumbnails: ["/images/products/nanoplastiateratment.jpeg"],
//       previews: ["/images/products/nanoplastiateratment.jpeg"],
//     },
//   },
//   {
//     title: "IMAXIA Professional Nano Mask (1000ml)",
//     description:
//       "Deep nourishing hair mask for dry, dull, and lackluster hair. Works in under 10 minutes to make hair softer, smoother, and shinier. Formulated with Rice & Silk Protein to improve strand texture and boost elasticity, crafted for Indian hair types and textures.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 4,
//     imgs: {
//       thumbnails: ["/images/products/nanomask1000ml.jpeg"],
//       previews: ["/images/products/nanomask1000ml.jpeg"],
//     },
//   },
//   {
//     title: "IMAXIA Professional Nano Mask (200ml)",
//     description:
//       "Deep nourishing hair mask for dry, dull, and lackluster hair. Works in under 10 minutes to make hair softer, smoother, and shinier. Formulated with Rice & Silk Protein to improve strand texture and boost elasticity, crafted for Indian hair types and textures.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 5,
//     imgs: {
//       thumbnails: ["/images/products/nanomask200ml.jpeg"],
//       previews: ["/images/products/nanomask200ml.jpeg"],
//     },
//   },

//   // ✅ BLUE BUTOS RANGE
//   {
//     title: "IMAXIA Professional Blue Butos Shampoo (1000ml)",
//     description:
//       "After-smoothing shampoo that gently cleanses and detangles while helping reduce hair fall and repair damage. Contains Argan Oil and plant-based linoline for moisturization, plus hydrolysed collagen complex to protect hair when using hot styling tools.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 6,
//     imgs: {
//       thumbnails: ["/images/products/bluebutossshampoo100ml.jpeg"],
//       previews: ["/images/products/bluebutossshampoo100ml.jpeg"],
//     },
//   },
//   {
//     title: "IMAXIA Professional Blue Butos Shampoo (300ml)",
//     description:
//       "After-smoothing shampoo that gently cleanses and detangles while helping reduce hair fall and repair damage. Contains Argan Oil and plant-based linoline for moisturization, plus hydrolysed collagen complex to protect hair when using hot styling tools.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 7,
//     imgs: {
//       thumbnails: ["/images/products/bluebutosshampoo.jpeg"],
//       previews: ["/images/products/bluebutosshampoo.jpeg"],
//     },
//   },

//   // ✅ EXTRA PRODUCT (Nanoplastia shown again in brochure)
//   {
//     title: "IMAXIA Professional Nanoplastia Treatment (Blue Butos Page - 1000ml)",
//     description:
//       "Nanoplastia treatment displayed again in the brochure under Blue Butos section. Formaldehyde-free single-sitting formula with amino acids, Argan Oil, and Acai Berry that repairs damaged hair, reduces frizz, and improves shine and smoothness.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 8,
//     imgs: {
//       thumbnails: ["/images/products/nanoplastiateratment.jpeg"],
//       previews: ["/images/products/nanoplastiateratment.jpeg"],
//     },
//   },

//   {
//     title: "IMAXIA Professional Blue Butos Mask (1000ml)",
//     description:
//       "Intense shine hair mask that deeply nourishes dry and dull hair, leaving it softer, smoother, and shinier in under 10 minutes. Enriched with Rice & Silk Protein to strengthen texture and boost elasticity, ideal for Indian hair types.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 9,
//     imgs: {
//       thumbnails: ["/images/products/bluebuttosmask100ml.jpeg"],
//       previews: ["/images/products/bluebuttosmask100ml.jpeg"],
//     },
//   },
//   {
//     title: "IMAXIA Professional Blue Butos Mask (200ml)",
//     description:
//       "Intense shine hair mask that deeply nourishes dry and dull hair, leaving it softer, smoother, and shinier in under 10 minutes. Enriched with Rice & Silk Protein to strengthen texture and boost elasticity, ideal for Indian hair types.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 10,
//     imgs: {
//       thumbnails: ["/images/products/bluebuttosmask.jpeg"],
//       previews: ["/images/products/bluebuttosmask.jpeg"],
//     },
//   },

//   // ✅ OTHER PRODUCTS
//   {
//     title: "IMAXIA Professional Purified Shampoo (Clarifying Shampoo)",
//     description:
//       "Deep cleansing clarifying shampoo designed to remove heavy metal buildup, excess oil, and residue caused by styling products, pollution, and hard water. Helps prepare the cuticle for hair treatments. Recommended to use only a couple of times per week to avoid dryness.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 11,
//     imgs: {
//       thumbnails: ["/images/products/purifiedshampoo.jpeg"],
//       previews: ["/images/products/purifiedshampoo.jpeg"],
//     },
//   },
//   {
//     title: "IMAXIA Professional Repair Hair Spa",
//     description:
//       "Hair spa mask for dry, dull, and lifeless hair. Deeply nourishes strands, improves softness and smoothness, and adds shine. Formulated with Rice & Silk Protein to enhance hair texture and elasticity for a salon-like finish.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 12,
//     imgs: {
//       thumbnails: ["/images/products/hairspa.jpeg"],
//       previews: ["/images/products/hairspa.jpeg"],
//     },
//   },
//   {
//     title: "IMAXIA Professional Heat Protecting Spray",
//     description:
//       "Advanced heat protection spray that shields hair from damage caused by blow dryers, flat irons, and curling irons. Helps maintain smoothness and shine while protecting hair. Infused with Argan Oil for added softness and manageability.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 13,
//     imgs: {
//       thumbnails: ["/images/products/heatprotectingspray.jpeg"],
//       previews: ["/images/products/heatprotectingspray.jpeg"],
//     },
//   },
//   {
//     title: "IMAXIA Professional Argan Oil",
//     description:
//       "Lightweight, non-greasy natural oil rich in Vitamin E, antioxidants, and essential fatty acids. Deeply nourishes hair, smooths frizz, adds instant shine, and helps repair dry and damaged strands while keeping hair soft, silky, and manageable.",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 14,
//     imgs: {
//       thumbnails: ["/images/products/argonoil1.jpeg"],
//       previews: ["/images/products/argonoil1.jpeg"],
//     },
//   },
// ];

// export default shopData;




// import { Product } from "@/types/product";

// const shopData: Product[] = [
//   {
//     title: "IMAXIA Professional Nano Shampoo (1000ml)",
//     description: "Hair-strengthening shampoo formulated for after-smoothing service. Gently cleanses and detangles while helping repair damaged hair, reduce hair fall, and improve softness. Enriched with Argan Oil, plant-based linoline, and hydrolysed collagen complex for heat styling protection.",
//     longDescription: "IMAXIA Nano Shampoo is specifically formulated for after-smoothing service. It gently cleanses and detangles the hair to maintain and prolong the cosmetic results. This post shampoo contains Argan Oil and Plant Base Linoline to moisturize the strands and Hydrolysed Collagen Complex to protect the hair while using hot styling tools. This hair-strengthening shampoo repairs damaged hair and improves its strength and softness to reduce hair fall. Suitable for colour treated hair and hair fall repair.",
//     keyBenefits: ["Repairs damaged hair", "Reduces hair fall", "Maintains smoothing results", "Heat styling protection", "Improves softness and strength"],
//     keyIngredients: ["Argan Oil", "Plant-Based Linoline", "Hydrolysed Collagen Complex"],
//     availableSizes: ["1000ml", "300ml"],
//     suitableFor: "Colour treated hair, hair fall repair, all hair types",
//     usage: "Use after smoothing service. Apply to wet hair, lather gently, rinse thoroughly.",
//     tag: "Sulphate Free",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 1,
//     imgs: { thumbnails: ["/images/products/nanoshampoo1000ml-removebg-preview.png"], previews: ["/images/products/nanoshampoo1000ml-removebg-preview.png"] },
//   },
//   {
//     title: "IMAXIA Professional Nano Shampoo (300ml)",
//     description: "Hair-strengthening shampoo formulated for after-smoothing service. Gently cleanses and detangles while helping repair damaged hair, reduce hair fall, and improve softness. Enriched with Argan Oil, plant-based linoline, and hydrolysed collagen complex for heat styling protection.",
//     longDescription: "IMAXIA Nano Shampoo is specifically formulated for after-smoothing service. It gently cleanses and detangles the hair to maintain and prolong the cosmetic results. This post shampoo contains Argan Oil and Plant Base Linoline to moisturize the strands and Hydrolysed Collagen Complex to protect the hair while using hot styling tools. This hair-strengthening shampoo repairs damaged hair and improves its strength and softness to reduce hair fall. Suitable for colour treated hair and hair fall repair.",
//     keyBenefits: ["Repairs damaged hair", "Reduces hair fall", "Maintains smoothing results", "Heat styling protection", "Improves softness and strength"],
//     keyIngredients: ["Argan Oil", "Plant-Based Linoline", "Hydrolysed Collagen Complex"],
//     availableSizes: ["1000ml", "300ml"],
//     suitableFor: "Colour treated hair, hair fall repair, all hair types",
//     usage: "Use after smoothing service. Apply to wet hair, lather gently, rinse thoroughly.",
//     tag: "Sulphate Free",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 2,
//     imgs: { thumbnails: ["/images/products/nanoshampoo.jpeg"], previews: ["/images/products/nanoshampoo.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Nanoplastia Treatment (1000ml)",
//     description: "Formaldehyde-free single-sitting nanoplastia treatment designed to repair damaged hair, reduce frizz, and improve texture. Infused with amino acids, Argan Oil, and Acai Berry to seal the cuticle, lock in moisture, and deliver smooth, shiny, frizz-free results.",
//     longDescription: "IMAXIA Nanoplastia Treatment is a revolutionary procedure that aims to repair damaged hair, reduce frizz, and enhance the overall appearance and texture of the locks. It utilizes a formaldehyde-free, single sitting formulation infused with Amino Acids, Argan Oil and Acai Berry that penetrates deep into the hair to repair damage at the molecular level. Our unique formula seals the cuticle, locks in moisture and gives unparalleled shine and smoothness, leaving hair frizz free with no harsh chemical smells. Suitable for various hair types and can be customized based on individual needs.",
//     keyBenefits: ["Repairs damage at molecular level", "Reduces frizz completely", "Unparalleled shine and smoothness", "No harsh chemical smells", "Customizable for all hair types"],
//     keyIngredients: ["Amino Acids", "Argan Oil", "Acai Berry"],
//     availableSizes: ["1000ml"],
//     suitableFor: "All hair types, customizable based on individual needs",
//     usage: "Single sitting professional treatment. Apply evenly, process, then seal with heat.",
//     tag: "0% Formaldehyde",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 3,
//     imgs: { thumbnails: ["/images/products/nanoplastiateratment.jpeg"], previews: ["/images/products/nanoplastiateratment.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Nano Mask (1000ml)",
//     description: "Deep nourishing hair mask for dry, dull, and lackluster hair. Works in under 10 minutes to make hair softer, smoother, and shinier. Formulated with Rice and Silk Protein to improve strand texture and boost elasticity, crafted for Indian hair types and textures.",
//     longDescription: "Struggling with dry, dull, and lackluster hair? Meet IMAXIA Nano Mask which nourishes your locks deeply, leaving them softer, smoother and shinier in under 10 minutes. Formulated with Rice and Silk Protein, the hair mask penetrates deeply into the hair shaft and improves the texture of the strands while boosting elasticity. Enriched with our signature Shine Tonic, the hair mask adds a glossy shine to locks, leaving them softer, smoother, and manageable like you just left the salon. The Intense Shine Hair Mask is crafted especially for Indian hair types, textures, and lengths.",
//     keyBenefits: ["Works in under 10 minutes", "Deeply nourishes dry and dull hair", "Adds glossy salon-like shine", "Boosts strand elasticity", "Crafted for Indian hair types"],
//     keyIngredients: ["Rice Protein", "Silk Protein", "Signature Shine Tonic"],
//     availableSizes: ["1000ml", "200ml"],
//     suitableFor: "Dry, dull, and lackluster hair, especially Indian hair types",
//     usage: "Apply to clean, damp hair. Leave for 5 to 10 minutes, then rinse thoroughly.",
//     tag: "Intense Shine",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 4,
//     imgs: { thumbnails: ["/images/products/nanomask1000ml.jpeg"], previews: ["/images/products/nanomask1000ml.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Nano Mask (200ml)",
//     description: "Deep nourishing hair mask for dry, dull, and lackluster hair. Works in under 10 minutes to make hair softer, smoother, and shinier. Formulated with Rice and Silk Protein to improve strand texture and boost elasticity, crafted for Indian hair types and textures.",
//     longDescription: "Struggling with dry, dull, and lackluster hair? Meet IMAXIA Nano Mask which nourishes your locks deeply, leaving them softer, smoother and shinier in under 10 minutes. Formulated with Rice and Silk Protein, the hair mask penetrates deeply into the hair shaft and improves the texture of the strands while boosting elasticity. Enriched with our signature Shine Tonic, the hair mask adds a glossy shine to locks, leaving them softer, smoother, and manageable like you just left the salon. The Intense Shine Hair Mask is crafted especially for Indian hair types, textures, and lengths.",
//     keyBenefits: ["Works in under 10 minutes", "Deeply nourishes dry and dull hair", "Adds glossy salon-like shine", "Boosts strand elasticity", "Crafted for Indian hair types"],
//     keyIngredients: ["Rice Protein", "Silk Protein", "Signature Shine Tonic"],
//     availableSizes: ["1000ml", "200ml"],
//     suitableFor: "Dry, dull, and lackluster hair, especially Indian hair types",
//     usage: "Apply to clean, damp hair. Leave for 5 to 10 minutes, then rinse thoroughly.",
//     tag: "Intense Shine",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 5,
//     imgs: { thumbnails: ["/images/products/nanomask200ml.jpeg"], previews: ["/images/products/nanomask200ml.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Blue Butos Shampoo (1000ml)",
//     description: "After-smoothing shampoo that gently cleanses and detangles while helping reduce hair fall and repair damage. Contains Argan Oil and plant-based linoline for moisturization, plus hydrolysed collagen complex to protect hair when using hot styling tools.",
//     longDescription: "IMAXIA Blue Butos Shampoo is specifically formulated for after-smoothing service. It gently cleanses and detangles the hair to maintain and prolong the cosmetic results. This post shampoo contains Argan Oil and Plant Base Linoline to moisturize the strands and Hydrolysed Collagen Complex to protect the hair while using hot styling tools. This hair-strengthening shampoo repairs damaged hair and improves its strength and softness to reduce hair fall. Ideal for use after any Blue Butos treatment.",
//     keyBenefits: ["Maintains Blue Butos treatment results", "Reduces hair fall", "Repairs damaged hair", "Moisturizes and strengthens strands", "Heat styling protection"],
//     keyIngredients: ["Argan Oil", "Plant-Based Linoline", "Hydrolysed Collagen Complex"],
//     availableSizes: ["1000ml", "300ml"],
//     suitableFor: "Colour treated hair, post-smoothing, all hair types",
//     usage: "Use after Blue Butos treatment. Apply to wet hair, lather gently, rinse thoroughly.",
//     tag: "Sulphate Free",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 6,
//     imgs: { thumbnails: ["/images/products/bluebutossshampoo100ml.jpeg"], previews: ["/images/products/bluebutossshampoo100ml.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Blue Butos Shampoo (300ml)",
//     description: "After-smoothing shampoo that gently cleanses and detangles while helping reduce hair fall and repair damage. Contains Argan Oil and plant-based linoline for moisturization, plus hydrolysed collagen complex to protect hair when using hot styling tools.",
//     longDescription: "IMAXIA Blue Butos Shampoo is specifically formulated for after-smoothing service. It gently cleanses and detangles the hair to maintain and prolong the cosmetic results. This post shampoo contains Argan Oil and Plant Base Linoline to moisturize the strands and Hydrolysed Collagen Complex to protect the hair while using hot styling tools. This hair-strengthening shampoo repairs damaged hair and improves its strength and softness to reduce hair fall. Ideal for use after any Blue Butos treatment.",
//     keyBenefits: ["Maintains Blue Butos treatment results", "Reduces hair fall", "Repairs damaged hair", "Moisturizes and strengthens strands", "Heat styling protection"],
//     keyIngredients: ["Argan Oil", "Plant-Based Linoline", "Hydrolysed Collagen Complex"],
//     availableSizes: ["1000ml", "300ml"],
//     suitableFor: "Colour treated hair, post-smoothing, all hair types",
//     usage: "Use after Blue Butos treatment. Apply to wet hair, lather gently, rinse thoroughly.",
//     tag: "Sulphate Free",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 7,
//     imgs: { thumbnails: ["/images/products/bluebutosshampoo.jpeg"], previews: ["/images/products/bluebutosshampoo.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Nanoplastia Treatment (Blue Butos Page - 1000ml)",
//     description: "Nanoplastia treatment displayed again in the brochure under Blue Butos section. Formaldehyde-free single-sitting formula with amino acids, Argan Oil, and Acai Berry that repairs damaged hair, reduces frizz, and improves shine and smoothness.",
//     longDescription: "IMAXIA Nanoplastia Treatment is a revolutionary procedure that aims to repair damaged hair, reduce frizz, and enhance the overall appearance and texture of the locks. It utilizes a formaldehyde-free, single sitting formulation infused with Amino Acids, Argan Oil and Acai Berry that penetrates deep into the hair to repair damage at the molecular level. Our unique formula seals the cuticle, locks in moisture and gives unparalleled shine and smoothness, leaving hair frizz free with no harsh chemical smells.",
//     keyBenefits: ["Repairs damage at molecular level", "Reduces frizz completely", "Unparalleled shine and smoothness", "No harsh chemical smells", "Customizable for all hair types"],
//     keyIngredients: ["Amino Acids", "Argan Oil", "Acai Berry"],
//     availableSizes: ["1000ml"],
//     suitableFor: "All hair types, customizable based on individual needs",
//     usage: "Single sitting professional treatment. Apply evenly, process, then seal with heat.",
//     tag: "0% Formaldehyde",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 8,
//     imgs: { thumbnails: ["/images/products/nanoplastiateratment.jpeg"], previews: ["/images/products/nanoplastiateratment.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Blue Butos Mask (1000ml)",
//     description: "Intense shine hair mask that deeply nourishes dry and dull hair, leaving it softer, smoother, and shinier in under 10 minutes. Enriched with Rice and Silk Protein to strengthen texture and boost elasticity, ideal for Indian hair types.",
//     longDescription: "Struggling with dry, dull, and lackluster hair? Meet IMAXIA Blue Butos Mask which nourishes your locks deeply, leaving them softer, smoother and shinier in under 10 minutes. Formulated with Rice and Silk Protein, the hair mask penetrates deeply into the hair shaft and improves the texture of the strands while boosting elasticity. Enriched with our signature Shine Tonic, the hair mask adds a glossy shine to locks, leaving them softer, smoother, and manageable like you just left the salon. Crafted especially for Indian hair types, textures, and lengths.",
//     keyBenefits: ["Works in under 10 minutes", "Makes hair silky, shiny and smooth", "Replenishes lost keratin", "Reduces frizz and boosts elasticity", "Ideal for Indian hair types"],
//     keyIngredients: ["Rice Protein", "Silk Protein", "Keratin Complex", "Signature Shine Tonic"],
//     availableSizes: ["1000ml", "200ml"],
//     suitableFor: "Dry, dull hair, especially Indian hair types and textures",
//     usage: "Apply to clean, damp hair. Leave for 5 to 10 minutes, then rinse thoroughly.",
//     tag: "Intense Shine",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 9,
//     imgs: { thumbnails: ["/images/products/bluebuttosmask100ml.jpeg"], previews: ["/images/products/bluebuttosmask100ml.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Blue Butos Mask (200ml)",
//     description: "Intense shine hair mask that deeply nourishes dry and dull hair, leaving it softer, smoother, and shinier in under 10 minutes. Enriched with Rice and Silk Protein to strengthen texture and boost elasticity, ideal for Indian hair types.",
//     longDescription: "Struggling with dry, dull, and lackluster hair? Meet IMAXIA Blue Butos Mask which nourishes your locks deeply, leaving them softer, smoother and shinier in under 10 minutes. Formulated with Rice and Silk Protein, the hair mask penetrates deeply into the hair shaft and improves the texture of the strands while boosting elasticity. Enriched with our signature Shine Tonic, the hair mask adds a glossy shine to locks, leaving them softer, smoother, and manageable like you just left the salon. Crafted especially for Indian hair types, textures, and lengths.",
//     keyBenefits: ["Works in under 10 minutes", "Makes hair silky, shiny and smooth", "Replenishes lost keratin", "Reduces frizz and boosts elasticity", "Ideal for Indian hair types"],
//     keyIngredients: ["Rice Protein", "Silk Protein", "Keratin Complex", "Signature Shine Tonic"],
//     availableSizes: ["1000ml", "200ml"],
//     suitableFor: "Dry, dull hair, especially Indian hair types and textures",
//     usage: "Apply to clean, damp hair. Leave for 5 to 10 minutes, then rinse thoroughly.",
//     tag: "Intense Shine",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 10,
//     imgs: { thumbnails: ["/images/products/bluebuttosmask.jpeg"], previews: ["/images/products/bluebuttosmask.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Purified Shampoo (Clarifying Shampoo)",
//     description: "Deep cleansing clarifying shampoo designed to remove heavy metal buildup, excess oil, and residue caused by styling products, pollution, and hard water. Helps prepare the cuticle for hair treatments. Recommended to use only a couple of times per week to avoid dryness.",
//     longDescription: "IMAXIA Purified Shampoo is a clarifying shampoo designed and developed to deep clean the hair follicle and remove heavy metal buildups, oil and residue caused by using products, pollution and hard water. It also enhances the cleansing action, resulting in the process of cuticle preparation for all types of hair treatment. Note: Using this shampoo more than a couple of times per week can leave your hair dry and dull. You may also see some flyaway and frizz with overuse.",
//     keyBenefits: ["Removes heavy metal buildup", "Eliminates product residue and pollution", "Deep cleans hair follicle", "Prepares cuticle for treatments", "Removes hard water deposits"],
//     keyIngredients: ["Clarifying Complex", "Deep Cleanse Formula"],
//     availableSizes: ["Available on request"],
//     suitableFor: "All hair types, use before any professional hair treatment",
//     usage: "Use maximum 2 times per week. Apply to wet hair, lather, rinse. Do not overuse.",
//     tag: "Clarifying",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 11,
//     imgs: { thumbnails: ["/images/products/purifiedshampoo.jpeg"], previews: ["/images/products/purifiedshampoo.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Repair Hair Spa",
//     description: "Hair spa mask for dry, dull, and lifeless hair. Deeply nourishes strands, improves softness and smoothness, and adds shine. Formulated with Rice and Silk Protein to enhance hair texture and elasticity for a salon-like finish.",
//     longDescription: "IMAXIA Repair Hair Spa deeply nourishes dry, dull, and lifeless hair, leaving it softer, smoother and shinier in under 10 minutes. Formulated with Rice and Silk Protein, it penetrates deeply into the hair shaft and improves the texture of the strands while boosting elasticity. Enriched with our signature Shine Tonic, it adds a glossy shine to locks leaving them softer, smoother, and manageable like you just left the salon. Crafted especially for Indian hair types, textures, and lengths. For professional use only.",
//     keyBenefits: ["Salon-quality repair", "Deeply nourishes lifeless hair", "Adds instant gloss and shine", "Improves hair texture and elasticity", "Works in under 10 minutes"],
//     keyIngredients: ["Rice Protein", "Silk Protein", "Signature Shine Tonic"],
//     availableSizes: ["500ml"],
//     suitableFor: "Dry, dull, and damaged hair, Indian hair types",
//     usage: "Apply to clean, damp hair. Leave for 5 to 10 minutes then rinse. For professional use only.",
//     tag: "For Professional Use",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 12,
//     imgs: { thumbnails: ["/images/products/hairspa.jpeg"], previews: ["/images/products/hairspa.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Heat Protecting Spray",
//     description: "Advanced heat protection spray that shields hair from damage caused by blow dryers, flat irons, and curling irons. Helps maintain smoothness and shine while protecting hair. Infused with Argan Oil for added softness and manageability.",
//     longDescription: "Experience the power of heat protection for healthy, silky, and shiny hair with IMAXIA Heat Protecting Spray. Created with an advanced protection formula designed to shield hair from heat damage caused by blow dryers, flat irons, and curling irons. Infused with Argan Oil, it maintains smoothness and shine while protecting hair from thermal damage. A must-have step before any heat styling routine to keep hair healthy, manageable and full of shine.",
//     keyBenefits: ["Shields against blow dryer damage", "Protects from flat iron and curling iron heat", "Maintains smoothness and shine", "Infused with Argan Oil", "Keeps hair healthy and manageable"],
//     keyIngredients: ["Argan Oil", "Advanced Heat Protection Complex"],
//     availableSizes: ["200ml"],
//     suitableFor: "All hair types, especially those who use heat styling tools regularly",
//     usage: "Spray evenly on damp or dry hair before heat styling. Do not rinse.",
//     tag: "Heat Protection",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 13,
//     imgs: { thumbnails: ["/images/products/heatprotectingspray.jpeg"], previews: ["/images/products/heatprotectingspray.jpeg"] },
//   },
//   {
//     title: "IMAXIA Professional Argan Oil",
//     description: "Lightweight, non-greasy natural oil rich in Vitamin E, antioxidants, and essential fatty acids. Deeply nourishes hair, smooths frizz, adds instant shine, and helps repair dry and damaged strands while keeping hair soft, silky, and manageable.",
//     longDescription: "IMAXIA Professional Argan Oil is a lightweight, non-greasy natural oil rich in Vitamin E, antioxidants, and essential fatty acids. It deeply nourishes hair, smooths frizz, adds instant shine, and helps repair dry and damaged strands while keeping hair soft, silky, and manageable. Suitable for all hair types, it can be used as a finishing serum, overnight treatment, or added to your conditioner for an extra boost of hydration and shine.",
//     keyBenefits: ["Lightweight and non-greasy formula", "Smooths frizz instantly", "Adds brilliant shine", "Repairs dry and damaged strands", "Suitable for all hair types"],
//     keyIngredients: ["Pure Argan Oil", "Vitamin E", "Antioxidants", "Essential Fatty Acids"],
//     availableSizes: ["Available on request"],
//     suitableFor: "All hair types",
//     usage: "Apply a few drops to damp or dry hair. Can be used as a serum, overnight treatment or mixed into conditioner.",
//     tag: "100% Natural Oil",
//     category: "Haircare",
//     reviews: 0,
//     price: 0,
//     discountedPrice: 0,
//     id: 14,
//     imgs: { thumbnails: ["/images/products/argonoil1.jpeg"], previews: ["/images/products/argonoil1.jpeg"] },
//   },
// ];

// export default shopData;



























import { Product } from "@/types/product";

const shopData: Product[] = [
  {
    title: "IMAXIA Professional Nano Shampoo (1000ml)",
    description: "Hair-strengthening shampoo formulated for after-smoothing service. Gently cleanses and detangles while helping repair damaged hair, reduce hair fall, and improve softness. Enriched with Argan Oil, plant-based linoline, and hydrolysed collagen complex for heat styling protection.",
    longDescription: "IMAXIA Nano Shampoo is specifically formulated for after-smoothing service. It gently cleanses and detangles the hair to maintain and prolong the cosmetic results. This post shampoo contains Argan Oil and Plant Base Linoline to moisturize the strands and Hydrolysed Collagen Complex to protect the hair while using hot styling tools. This hair-strengthening shampoo repairs damaged hair and improves its strength and softness to reduce hair fall. Suitable for colour treated hair and hair fall repair.",
    keyBenefits: ["Repairs damaged hair", "Reduces hair fall", "Maintains smoothing results", "Heat styling protection", "Improves softness and strength"],
    keyIngredients: ["Argan Oil", "Plant-Based Linoline", "Hydrolysed Collagen Complex"],
    availableSizes: ["1000ml", "300ml"],
    suitableFor: "Colour treated hair, hair fall repair, all hair types",
    usage: "Use after smoothing service. Apply to wet hair, lather gently, rinse thoroughly.",
    tag: "Sulphate Free",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 1,
    imgs: { thumbnails: ["/images/products/nanoshampoo1000ml-removebg-preview.png"], previews: ["/images/products/nanoshampoo1000ml-removebg-preview.png"] },
  },
  {
    title: "IMAXIA Professional Nano Shampoo (300ml)",
    description: "Hair-strengthening shampoo formulated for after-smoothing service. Gently cleanses and detangles while helping repair damaged hair, reduce hair fall, and improve softness. Enriched with Argan Oil, plant-based linoline, and hydrolysed collagen complex for heat styling protection.",
    longDescription: "IMAXIA Nano Shampoo is specifically formulated for after-smoothing service. It gently cleanses and detangles the hair to maintain and prolong the cosmetic results. This post shampoo contains Argan Oil and Plant Base Linoline to moisturize the strands and Hydrolysed Collagen Complex to protect the hair while using hot styling tools. This hair-strengthening shampoo repairs damaged hair and improves its strength and softness to reduce hair fall. Suitable for colour treated hair and hair fall repair.",
    keyBenefits: ["Repairs damaged hair", "Reduces hair fall", "Maintains smoothing results", "Heat styling protection", "Improves softness and strength"],
    keyIngredients: ["Argan Oil", "Plant-Based Linoline", "Hydrolysed Collagen Complex"],
    availableSizes: ["1000ml", "300ml"],
    suitableFor: "Colour treated hair, hair fall repair, all hair types",
    usage: "Use after smoothing service. Apply to wet hair, lather gently, rinse thoroughly.",
    tag: "Sulphate Free",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 2,
    imgs: { thumbnails: ["/images/products/nanoshampoo.jpeg"], previews: ["/images/products/nanoshampoo.jpeg"] },
  },
  {
    title: "IMAXIA Professional Nanoplastia Treatment (1000ml)",
    description: "Formaldehyde-free single-sitting nanoplastia treatment designed to repair damaged hair, reduce frizz, and improve texture. Infused with amino acids, Argan Oil, and Acai Berry to seal the cuticle, lock in moisture, and deliver smooth, shiny, frizz-free results.",
    longDescription: "IMAXIA Nanoplastia Treatment is a revolutionary procedure that aims to repair damaged hair, reduce frizz, and enhance the overall appearance and texture of the locks. It utilizes a formaldehyde-free, single sitting formulation infused with Amino Acids, Argan Oil and Acai Berry that penetrates deep into the hair to repair damage at the molecular level. Our unique formula seals the cuticle, locks in moisture and gives unparalleled shine and smoothness, leaving hair frizz free with no harsh chemical smells. Suitable for various hair types and can be customized based on individual needs.",
    keyBenefits: ["Repairs damage at molecular level", "Reduces frizz completely", "Unparalleled shine and smoothness", "No harsh chemical smells", "Customizable for all hair types"],
    keyIngredients: ["Amino Acids", "Argan Oil", "Acai Berry"],
    availableSizes: ["1000ml"],
    suitableFor: "All hair types, customizable based on individual needs",
    usage: "Single sitting professional treatment. Apply evenly, process, then seal with heat.",
    tag: "0% Formaldehyde",
    category: "Hair Treatment",
    reviews: 0, price: 0, discountedPrice: 0, id: 3,
    imgs: { thumbnails: ["/images/products/nanoplastiateratment-removebg-preview.png"], previews: ["/images/products/nanoplastiateratment-removebg-preview.png"] },
  },
  {
    title: "IMAXIA Professional Nano Mask (1000ml)",
    description: "Deep nourishing hair mask for dry, dull, and lackluster hair. Works in under 10 minutes to make hair softer, smoother, and shinier. Formulated with Rice and Silk Protein to improve strand texture and boost elasticity, crafted for Indian hair types and textures.",
    longDescription: "Struggling with dry, dull, and lackluster hair? Meet IMAXIA Nano Mask which nourishes your locks deeply, leaving them softer, smoother and shinier in under 10 minutes. Formulated with Rice and Silk Protein, the hair mask penetrates deeply into the hair shaft and improves the texture of the strands while boosting elasticity. Enriched with our signature Shine Tonic, the hair mask adds a glossy shine to locks, leaving them softer, smoother, and manageable like you just left the salon. The Intense Shine Hair Mask is crafted especially for Indian hair types, textures, and lengths.",
    keyBenefits: ["Works in under 10 minutes", "Deeply nourishes dry and dull hair", "Adds glossy salon-like shine", "Boosts strand elasticity", "Crafted for Indian hair types"],
    keyIngredients: ["Rice Protein", "Silk Protein", "Signature Shine Tonic"],
    availableSizes: ["1000ml", "200ml"],
    suitableFor: "Dry, dull, and lackluster hair, especially Indian hair types",
    usage: "Apply to clean, damp hair. Leave for 5 to 10 minutes, then rinse thoroughly.",
    tag: "Intense Shine",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 4,
    imgs: { thumbnails: ["/images/products/nanomask1000ml.jpeg"], previews: ["/images/products/nanomask1000ml.jpeg"] },
  },
  {
    title: "IMAXIA Professional Nano Mask (200ml)",
    description: "Deep nourishing hair mask for dry, dull, and lackluster hair. Works in under 10 minutes to make hair softer, smoother, and shinier. Formulated with Rice and Silk Protein to improve strand texture and boost elasticity, crafted for Indian hair types and textures.",
    longDescription: "Struggling with dry, dull, and lackluster hair? Meet IMAXIA Nano Mask which nourishes your locks deeply, leaving them softer, smoother and shinier in under 10 minutes. Formulated with Rice and Silk Protein, the hair mask penetrates deeply into the hair shaft and improves the texture of the strands while boosting elasticity. Enriched with our signature Shine Tonic, the hair mask adds a glossy shine to locks, leaving them softer, smoother, and manageable like you just left the salon. The Intense Shine Hair Mask is crafted especially for Indian hair types, textures, and lengths.",
    keyBenefits: ["Works in under 10 minutes", "Deeply nourishes dry and dull hair", "Adds glossy salon-like shine", "Boosts strand elasticity", "Crafted for Indian hair types"],
    keyIngredients: ["Rice Protein", "Silk Protein", "Signature Shine Tonic"],
    availableSizes: ["1000ml", "200ml"],
    suitableFor: "Dry, dull, and lackluster hair, especially Indian hair types",
    usage: "Apply to clean, damp hair. Leave for 5 to 10 minutes, then rinse thoroughly.",
    tag: "Intense Shine",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 5,
    imgs: { thumbnails: ["/images/products/nanomask200ml.jpeg"], previews: ["/images/products/nanomask200ml.jpeg"] },
  },
  {
    title: "IMAXIA Professional Blue Butos Shampoo (1000ml)",
    description: "After-smoothing shampoo that gently cleanses and detangles while helping reduce hair fall and repair damage. Contains Argan Oil and plant-based linoline for moisturization, plus hydrolysed collagen complex to protect hair when using hot styling tools.",
    longDescription: "IMAXIA Blue Butos Shampoo is specifically formulated for after-smoothing service. It gently cleanses and detangles the hair to maintain and prolong the cosmetic results. This post shampoo contains Argan Oil and Plant Base Linoline to moisturize the strands and Hydrolysed Collagen Complex to protect the hair while using hot styling tools. This hair-strengthening shampoo repairs damaged hair and improves its strength and softness to reduce hair fall. Ideal for use after any Blue Butos treatment.",
    keyBenefits: ["Maintains Blue Butos treatment results", "Reduces hair fall", "Repairs damaged hair", "Moisturizes and strengthens strands", "Heat styling protection"],
    keyIngredients: ["Argan Oil", "Plant-Based Linoline", "Hydrolysed Collagen Complex"],
    availableSizes: ["1000ml", "300ml"],
    suitableFor: "Colour treated hair, post-smoothing, all hair types",
    usage: "Use after Blue Butos treatment. Apply to wet hair, lather gently, rinse thoroughly.",
    tag: "Sulphate Free",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 6,
    imgs: { thumbnails: ["/images/products/bluebutossshampoo100ml.jpeg"], previews: ["/images/products/bluebutossshampoo100ml.jpeg"] },
  },
  {
    title: "IMAXIA Professional Blue Butos Shampoo (300ml)",
    description: "After-smoothing shampoo that gently cleanses and detangles while helping reduce hair fall and repair damage. Contains Argan Oil and plant-based linoline for moisturization, plus hydrolysed collagen complex to protect hair when using hot styling tools.",
    longDescription: "IMAXIA Blue Butos Shampoo is specifically formulated for after-smoothing service. It gently cleanses and detangles the hair to maintain and prolong the cosmetic results. This post shampoo contains Argan Oil and Plant Base Linoline to moisturize the strands and Hydrolysed Collagen Complex to protect the hair while using hot styling tools. This hair-strengthening shampoo repairs damaged hair and improves its strength and softness to reduce hair fall. Ideal for use after any Blue Butos treatment.",
    keyBenefits: ["Maintains Blue Butos treatment results", "Reduces hair fall", "Repairs damaged hair", "Moisturizes and strengthens strands", "Heat styling protection"],
    keyIngredients: ["Argan Oil", "Plant-Based Linoline", "Hydrolysed Collagen Complex"],
    availableSizes: ["1000ml", "300ml"],
    suitableFor: "Colour treated hair, post-smoothing, all hair types",
    usage: "Use after Blue Butos treatment. Apply to wet hair, lather gently, rinse thoroughly.",
    tag: "Sulphate Free",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 7,
    imgs: { thumbnails: ["/images/products/bluebutosshampoo.jpeg"], previews: ["/images/products/bluebutosshampoo.jpeg"] },
  },
  {
    title: "IMAXIA Professional Nanoplastia Treatment (Blue Butos Page - 1000ml)",
    description: "Nanoplastia treatment displayed again in the brochure under Blue Butos section. Formaldehyde-free single-sitting formula with amino acids, Argan Oil, and Acai Berry that repairs damaged hair, reduces frizz, and improves shine and smoothness.",
    longDescription: "IMAXIA Nanoplastia Treatment is a revolutionary procedure that aims to repair damaged hair, reduce frizz, and enhance the overall appearance and texture of the locks. It utilizes a formaldehyde-free, single sitting formulation infused with Amino Acids, Argan Oil and Acai Berry that penetrates deep into the hair to repair damage at the molecular level. Our unique formula seals the cuticle, locks in moisture and gives unparalleled shine and smoothness, leaving hair frizz free with no harsh chemical smells.",
    keyBenefits: ["Repairs damage at molecular level", "Reduces frizz completely", "Unparalleled shine and smoothness", "No harsh chemical smells", "Customizable for all hair types"],
    keyIngredients: ["Amino Acids", "Argan Oil", "Acai Berry"],
    availableSizes: ["1000ml"],
    suitableFor: "All hair types, customizable based on individual needs",
    usage: "Single sitting professional treatment. Apply evenly, process, then seal with heat.",
    tag: "0% Formaldehyde",
    category: "Hair Treatment",
    reviews: 0, price: 0, discountedPrice: 0, id: 8,
    imgs: { thumbnails: ["/images/products/nanoplastiateratment.jpeg"], previews: ["/images/products/nanoplastiateratment.jpeg"] },
  },
  {
    title: "IMAXIA Professional Blue Butos Mask (1000ml)",
    description: "Intense shine hair mask that deeply nourishes dry and dull hair, leaving it softer, smoother, and shinier in under 10 minutes. Enriched with Rice and Silk Protein to strengthen texture and boost elasticity, ideal for Indian hair types.",
    longDescription: "Struggling with dry, dull, and lackluster hair? Meet IMAXIA Blue Butos Mask which nourishes your locks deeply, leaving them softer, smoother and shinier in under 10 minutes. Formulated with Rice and Silk Protein, the hair mask penetrates deeply into the hair shaft and improves the texture of the strands while boosting elasticity. Enriched with our signature Shine Tonic, the hair mask adds a glossy shine to locks, leaving them softer, smoother, and manageable like you just left the salon. Crafted especially for Indian hair types, textures, and lengths.",
    keyBenefits: ["Works in under 10 minutes", "Makes hair silky, shiny and smooth", "Replenishes lost keratin", "Reduces frizz and boosts elasticity", "Ideal for Indian hair types"],
    keyIngredients: ["Rice Protein", "Silk Protein", "Keratin Complex", "Signature Shine Tonic"],
    availableSizes: ["1000ml", "200ml"],
    suitableFor: "Dry, dull hair, especially Indian hair types and textures",
    usage: "Apply to clean, damp hair. Leave for 5 to 10 minutes, then rinse thoroughly.",
    tag: "Intense Shine",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 9,
    imgs: { thumbnails: ["/images/products/bluebuttosmask100ml.jpeg"], previews: ["/images/products/bluebuttosmask100ml.jpeg"] },
  },
  {
    title: "IMAXIA Professional Blue Butos Mask (200ml)",
    description: "Intense shine hair mask that deeply nourishes dry and dull hair, leaving it softer, smoother, and shinier in under 10 minutes. Enriched with Rice and Silk Protein to strengthen texture and boost elasticity, ideal for Indian hair types.",
    longDescription: "Struggling with dry, dull, and lackluster hair? Meet IMAXIA Blue Butos Mask which nourishes your locks deeply, leaving them softer, smoother and shinier in under 10 minutes. Formulated with Rice and Silk Protein, the hair mask penetrates deeply into the hair shaft and improves the texture of the strands while boosting elasticity. Enriched with our signature Shine Tonic, the hair mask adds a glossy shine to locks, leaving them softer, smoother, and manageable like you just left the salon. Crafted especially for Indian hair types, textures, and lengths.",
    keyBenefits: ["Works in under 10 minutes", "Makes hair silky, shiny and smooth", "Replenishes lost keratin", "Reduces frizz and boosts elasticity", "Ideal for Indian hair types"],
    keyIngredients: ["Rice Protein", "Silk Protein", "Keratin Complex", "Signature Shine Tonic"],
    availableSizes: ["1000ml", "200ml"],
    suitableFor: "Dry, dull hair, especially Indian hair types and textures",
    usage: "Apply to clean, damp hair. Leave for 5 to 10 minutes, then rinse thoroughly.",
    tag: "Intense Shine",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 10,
    imgs: { thumbnails: ["/images/products/bluebuttosmask.jpeg"], previews: ["/images/products/bluebuttosmask.jpeg"] },
  },
  {
    title: "IMAXIA Professional Purified Shampoo (Clarifying Shampoo)",
    description: "Deep cleansing clarifying shampoo designed to remove heavy metal buildup, excess oil, and residue caused by styling products, pollution, and hard water. Helps prepare the cuticle for hair treatments. Recommended to use only a couple of times per week to avoid dryness.",
    longDescription: "IMAXIA Purified Shampoo is a clarifying shampoo designed and developed to deep clean the hair follicle and remove heavy metal buildups, oil and residue caused by using products, pollution and hard water. It also enhances the cleansing action, resulting in the process of cuticle preparation for all types of hair treatment. Note: Using this shampoo more than a couple of times per week can leave your hair dry and dull. You may also see some flyaway and frizz with overuse.",
    keyBenefits: ["Removes heavy metal buildup", "Eliminates product residue and pollution", "Deep cleans hair follicle", "Prepares cuticle for treatments", "Removes hard water deposits"],
    keyIngredients: ["Clarifying Complex", "Deep Cleanse Formula"],
    availableSizes: ["Available on request"],
    suitableFor: "All hair types, use before any professional hair treatment",
    usage: "Use maximum 2 times per week. Apply to wet hair, lather, rinse. Do not overuse.",
    tag: "Clarifying",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 11,
    imgs: { thumbnails: ["/images/products/purifiedshampoo.jpeg"], previews: ["/images/products/purifiedshampoo.jpeg"] },
  },
  {
    title: "IMAXIA Professional Repair Hair Spa",
    description: "Hair spa mask for dry, dull, and lifeless hair. Deeply nourishes strands, improves softness and smoothness, and adds shine. Formulated with Rice and Silk Protein to enhance hair texture and elasticity for a salon-like finish.",
    longDescription: "IMAXIA Repair Hair Spa deeply nourishes dry, dull, and lifeless hair, leaving it softer, smoother and shinier in under 10 minutes. Formulated with Rice and Silk Protein, it penetrates deeply into the hair shaft and improves the texture of the strands while boosting elasticity. Enriched with our signature Shine Tonic, it adds a glossy shine to locks leaving them softer, smoother, and manageable like you just left the salon. Crafted especially for Indian hair types, textures, and lengths. For professional use only.",
    keyBenefits: ["Salon-quality repair", "Deeply nourishes lifeless hair", "Adds instant gloss and shine", "Improves hair texture and elasticity", "Works in under 10 minutes"],
    keyIngredients: ["Rice Protein", "Silk Protein", "Signature Shine Tonic"],
    availableSizes: ["500ml"],
    suitableFor: "Dry, dull, and damaged hair, Indian hair types",
    usage: "Apply to clean, damp hair. Leave for 5 to 10 minutes then rinse. For professional use only.",
    tag: "For Professional Use",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 12,
    imgs: { thumbnails: ["/images/products/hairspa.jpeg"], previews: ["/images/products/hairspa.jpeg"] },
  },
  {
    title: "IMAXIA Professional Heat Protecting Spray",
    description: "Advanced heat protection spray that shields hair from damage caused by blow dryers, flat irons, and curling irons. Helps maintain smoothness and shine while protecting hair. Infused with Argan Oil for added softness and manageability.",
    longDescription: "Experience the power of heat protection for healthy, silky, and shiny hair with IMAXIA Heat Protecting Spray. Created with an advanced protection formula designed to shield hair from heat damage caused by blow dryers, flat irons, and curling irons. Infused with Argan Oil, it maintains smoothness and shine while protecting hair from thermal damage. A must-have step before any heat styling routine to keep hair healthy, manageable and full of shine.",
    keyBenefits: ["Shields against blow dryer damage", "Protects from flat iron and curling iron heat", "Maintains smoothness and shine", "Infused with Argan Oil", "Keeps hair healthy and manageable"],
    keyIngredients: ["Argan Oil", "Advanced Heat Protection Complex"],
    availableSizes: ["200ml"],
    suitableFor: "All hair types, especially those who use heat styling tools regularly",
    usage: "Spray evenly on damp or dry hair before heat styling. Do not rinse.",
    tag: "Heat Protection",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 13,
    imgs: { thumbnails: ["/images/products/heatprotectingspray.jpeg"], previews: ["/images/products/heatprotectingspray.jpeg"] },
  },
  {
    title: "IMAXIA Professional Argan Oil",
    description: "Lightweight, non-greasy natural oil rich in Vitamin E, antioxidants, and essential fatty acids. Deeply nourishes hair, smooths frizz, adds instant shine, and helps repair dry and damaged strands while keeping hair soft, silky, and manageable.",
    longDescription: "IMAXIA Professional Argan Oil is a lightweight, non-greasy natural oil rich in Vitamin E, antioxidants, and essential fatty acids. It deeply nourishes hair, smooths frizz, adds instant shine, and helps repair dry and damaged strands while keeping hair soft, silky, and manageable. Suitable for all hair types, it can be used as a finishing serum, overnight treatment, or added to your conditioner for an extra boost of hydration and shine.",
    keyBenefits: ["Lightweight and non-greasy formula", "Smooths frizz instantly", "Adds brilliant shine", "Repairs dry and damaged strands", "Suitable for all hair types"],
    keyIngredients: ["Pure Argan Oil", "Vitamin E", "Antioxidants", "Essential Fatty Acids"],
    availableSizes: ["Available on request"],
    suitableFor: "All hair types",
    usage: "Apply a few drops to damp or dry hair. Can be used as a serum, overnight treatment or mixed into conditioner.",
    tag: "100% Natural Oil",
    category: "Hair care",
    reviews: 0, price: 0, discountedPrice: 0, id: 14,
    imgs: { thumbnails: ["/images/products/argonoil1.jpeg"], previews: ["/images/products/argonoil1.jpeg"] },
  },
    {
    title: "IMAXIA Professional Argan Oil",
    description: "Lightweight, non-greasy natural oil rich in Vitamin E, antioxidants, and essential fatty acids. Deeply nourishes hair, smooths frizz, adds instant shine, and helps repair dry and damaged strands while keeping hair soft, silky, and manageable.",
    longDescription: "IMAXIA Professional Argan Oil is a lightweight, non-greasy natural oil rich in Vitamin E, antioxidants, and essential fatty acids. It deeply nourishes hair, smooths frizz, adds instant shine, and helps repair dry and damaged strands while keeping hair soft, silky, and manageable. Suitable for all hair types, it can be used as a finishing serum, overnight treatment, or added to your conditioner for an extra boost of hydration and shine.",
    keyBenefits: ["Lightweight and non-greasy formula", "Smooths frizz instantly", "Adds brilliant shine", "Repairs dry and damaged strands", "Suitable for all hair types"],
    keyIngredients: ["Pure Argan Oil", "Vitamin E", "Antioxidants", "Essential Fatty Acids"],
    availableSizes: ["Available on request"],
    suitableFor: "All hair types",
    usage: "Apply a few drops to damp or dry hair. Can be used as a serum, overnight treatment or mixed into conditioner.",
    tag: "100% Natural Oil",
    category: "Skin care",
    reviews: 0, price: 0, discountedPrice: 0, id: 15,
    imgs: { thumbnails: ["/images/products/argonoil1-removebg-preview.png"], previews: ["/images/products/argonoil1-removebg-preview.png"] },
  },
];

export default shopData;